name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  # Release $NEXT_PATCH_VERSION

  ## Changes
  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore

on:
  pull_request:
    branches:
      - release
      
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: '* No changes'
version-template: '$MAJOR.$MINOR.$PATCH$PRERELEASE'
version-resolver:
  major:
    labels: []
  minor:
    labels: []
  patch:
    labels: []
  default: 'patch'
sort-by: 'merged_at'
sort-direction: 'descending'
prerelease: false
include-pre-releases: false
pull-request-limit: 5
