name: Release Go Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go binaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/MSolGy-linux-amd64
          GOOS=linux   GOARCH=arm64 go build -o dist/MSolGy-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/MSolGy-windows-amd64.exe
          GOOS=darwin  GOARCH=amd64 go build -o dist/MSolGy-darwin-amd64
          GOOS=darwin  GOARCH=arm64 go build -o dist/MSolGy-darwin-arm64

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
